export default {
  SIGN_IN_BEGIN: "SIGN_IN_BEGIN",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  FORGOT_PASSWORD_BEGIN: "FORGOT_PASSWORD_BEGIN",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",
  SIGN_OUT: "SIGN_OUT",
  REFRESH_TOKEN_BEGIN: "REFRESH_TOKEN_BEGIN",
  REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS",
  REFRESH_TOKEN_FAILURE: "REFRESH_TOKEN_FAILURE"
};
